#!/bin/bash
echo "=========================================="
echo "Deploying Supabase Edge Function"
echo "=========================================="
echo ""
echo "Step 1: Login to Supabase"
echo "Run: supabase login"
echo ""
echo "Step 2: Link project"
echo "Run: supabase link --project-ref togpvwfxmydgitkwqdgd"
echo ""
echo "Step 3: Set secret"
echo "Run: supabase secrets set ALICLOUD_API_KEY=sk-f457a807f49f4c958636696c751f7533"
echo ""
echo "Step 4: Deploy function"
echo "Run: supabase functions deploy generate-content --project-ref togpvwfxmydgitkwqdgd"
echo ""
echo "=========================================="
echo "After deployment, test with:"
echo "=========================================="
echo ""
echo "curl -L -X POST 'https://togpvwfxmydgitkwqdgd.supabase.co/functions/v1/generate-content/generate-text' \\"
echo "  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZ3B2d2Z4bXlkZ2l0a3dxZGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyODg2NzMsImV4cCI6MjA4MTg2NDY3M30.5lFeW3Cbis7H4CqaLHrV1-13Z0piJpQ6a3gQmDJ7Y2Y' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  --data '{\"prompt\": \"測試\", \"job_type\": \"blog_post\", \"max_length\": 100}'"
