-- Seed AI Tools into Supabase
-- Run this in Supabase SQL Editor after running the initial migration

INSERT INTO public.ai_tools (
  slug, name, name_chinese, description, description_chinese,
  short_description, short_description_chinese, category,
  features, use_cases, pricing_info, tutorial_urls,
  website_url, is_featured, is_active, order_index
) VALUES
(
  'gamma',
  'Gamma',
  'Gamma',
  'Gamma is an AI-powered presentation tool that helps you create beautiful, engaging presentations in minutes. Simply describe what you want, and Gamma generates a professional presentation with slides, layouts, and content automatically.',
  'Gamma 是一個 AI 驅動的簡報工具，可幫助您在幾分鐘內創建精美、引人入勝的簡報。只需描述您想要的內容，Gamma 就會自動生成包含投影片、佈局和內容的專業簡報。',
  'AI-powered presentation tool that creates beautiful slides automatically',
  'AI 驅動的簡報工具，自動創建精美的投影片',
  '簡報製作',
  '["AI-generated presentations", "Multiple templates", "Export to PDF/PPT", "Real-time collaboration", "Custom branding"]'::jsonb,
  '["教學簡報製作", "課程內容展示", "學生作品展示", "培訓材料準備"]'::jsonb,
  '{"free": true, "plans": [{"name": "Free", "price": 0, "features": ["Limited presentations"]}, {"name": "Pro", "price": 10, "currency": "USD", "period": "month", "features": ["Unlimited presentations", "Custom branding"]}]}'::jsonb,
  '["https://gamma.app/docs", "https://www.youtube.com/watch?v=gamma-tutorial"]'::jsonb,
  'https://gamma.app',
  true,
  true,
  1
),
(
  'animaker',
  'Animaker',
  'Animaker',
  'Animaker is a cloud-based animation and video creation platform that allows users to create professional animated videos, presentations, and infographics without any design or animation skills. Perfect for creating engaging educational content.',
  'Animaker 是一個基於雲端的動畫和影片創作平台，讓用戶無需任何設計或動畫技能即可創建專業的動畫影片、簡報和信息圖表。非常適合創建引人入勝的教育內容。',
  'Cloud-based animation and video creation platform for educational content',
  '基於雲端的動畫和影片創作平台，用於教育內容',
  '影片製作',
  '["Drag-and-drop interface", "Thousands of templates", "Character builder", "Voice-over recording", "Multiple export formats"]'::jsonb,
  '["教學影片製作", "動畫課程內容", "學生專案展示", "宣傳影片製作"]'::jsonb,
  '{"free": true, "plans": [{"name": "Free", "price": 0, "features": ["Limited exports"]}, {"name": "Basic", "price": 10, "currency": "USD", "period": "month", "features": ["HD exports", "More templates"]}, {"name": "Starter", "price": 19, "currency": "USD", "period": "month", "features": ["Full HD", "No watermark"]}]}'::jsonb,
  '["https://www.animaker.com/help", "https://www.youtube.com/c/Animaker"]'::jsonb,
  'https://www.animaker.com',
  true,
  true,
  2
),
(
  'n8n',
  'n8n',
  'n8n',
  'n8n is a powerful workflow automation tool that allows you to connect different apps and services together. Create automated workflows to streamline your teaching tasks, manage student data, and integrate various educational tools.',
  'n8n 是一個強大的工作流程自動化工具，可讓您將不同的應用程式和服務連接在一起。創建自動化工作流程以簡化您的教學任務、管理學生數據並整合各種教育工具。',
  'Workflow automation platform to connect apps and automate tasks',
  '工作流程自動化平台，用於連接應用程式和自動化任務',
  '自動化工具',
  '["Visual workflow builder", "500+ integrations", "Self-hosted option", "Webhook support", "Custom nodes"]'::jsonb,
  '["教學流程自動化", "學生數據管理", "多平台內容同步", "通知系統設置"]'::jsonb,
  '{"free": true, "plans": [{"name": "Community", "price": 0, "features": ["Self-hosted", "Open source"]}, {"name": "Cloud", "price": 20, "currency": "USD", "period": "month", "features": ["Hosted", "Support"]}]}'::jsonb,
  '["https://docs.n8n.io", "https://www.youtube.com/c/n8n-io"]'::jsonb,
  'https://n8n.io',
  true,
  true,
  3
),
(
  'canva',
  'Canva',
  'Canva',
  'Canva is a graphic design platform that makes it easy to create professional designs for presentations, social media, posters, and more. With AI-powered features, it helps teachers create engaging visual content quickly.',
  'Canva 是一個圖形設計平台，可輕鬆為簡報、社交媒體、海報等創建專業設計。憑藉 AI 驅動的功能，它幫助教師快速創建引人入勝的視覺內容。',
  'Graphic design platform with AI features for creating visual content',
  '具有 AI 功能的圖形設計平台，用於創建視覺內容',
  '設計工具',
  '["Thousands of templates", "AI design tools", "Brand kit", "Team collaboration", "Export in multiple formats"]'::jsonb,
  '["教學材料設計", "海報和傳單製作", "社交媒體內容", "簡報美化"]'::jsonb,
  '{"free": true, "plans": [{"name": "Free", "price": 0, "features": ["Basic templates"]}, {"name": "Pro", "price": 12.99, "currency": "USD", "period": "month", "features": ["Premium templates", "Brand kit"]}]}'::jsonb,
  '["https://www.canva.com/designschool", "https://www.youtube.com/c/Canva"]'::jsonb,
  'https://www.canva.com',
  false,
  true,
  4
),
(
  'notion',
  'Notion',
  'Notion',
  'Notion is an all-in-one workspace that combines notes, docs, wikis, and databases. Perfect for organizing course materials, creating student wikis, and managing educational projects.',
  'Notion 是一個一體化工作空間，結合了筆記、文檔、維基和數據庫。非常適合組織課程材料、創建學生維基和管理教育項目。',
  'All-in-one workspace for notes, docs, and project management',
  '一體化工作空間，用於筆記、文檔和項目管理',
  '生產力工具',
  '["Unified workspace", "Database and views", "Templates gallery", "Team collaboration", "API access"]'::jsonb,
  '["課程材料組織", "學生專案管理", "協作筆記", "知識庫建立"]'::jsonb,
  '{"free": true, "plans": [{"name": "Free", "price": 0, "features": ["Personal use"]}, {"name": "Plus", "price": 8, "currency": "USD", "period": "month", "features": ["Team collaboration"]}]}'::jsonb,
  '["https://www.notion.so/help", "https://www.youtube.com/c/Notion"]'::jsonb,
  'https://www.notion.so',
  false,
  true,
  5
),
(
  'chatgpt',
  'ChatGPT',
  'ChatGPT',
  'ChatGPT is an AI-powered conversational assistant that can help with lesson planning, content creation, answering student questions, and providing personalized learning support.',
  'ChatGPT 是一個 AI 驅動的對話助手，可以幫助進行課程規劃、內容創建、回答學生問題和提供個性化學習支持。',
  'AI conversational assistant for education and content creation',
  '用於教育和內容創建的 AI 對話助手',
  'AI 助手',
  '["Natural language conversations", "Content generation", "Code assistance", "Multi-language support", "Custom instructions"]'::jsonb,
  '["課程內容生成", "作業輔導", "語言學習", "創意寫作"]'::jsonb,
  '{"free": true, "plans": [{"name": "Free", "price": 0, "features": ["GPT-3.5 access"]}, {"name": "Plus", "price": 20, "currency": "USD", "period": "month", "features": ["GPT-4 access", "Priority support"]}]}'::jsonb,
  '["https://help.openai.com", "https://www.youtube.com/c/OpenAI"]'::jsonb,
  'https://chat.openai.com',
  true,
  true,
  6
)
ON CONFLICT (slug) DO NOTHING;

