// This file will be auto-generated by Supabase CLI
// For now, we'll define a basic Database type
export type Database = {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          email: string | null;
          full_name: string | null;
          role: 'admin' | 'teacher' | 'student' | 'guest';
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          full_name?: string | null;
          role?: 'admin' | 'teacher' | 'student' | 'guest';
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          full_name?: string | null;
          role?: 'admin' | 'teacher' | 'student' | 'guest';
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_tools: {
        Row: {
          id: string;
          slug: string;
          name: string;
          name_chinese: string | null;
          description: string | null;
          description_chinese: string | null;
          short_description: string | null;
          short_description_chinese: string | null;
          category: string | null;
          icon_url: string | null;
          cover_image_url: string | null;
          features: string[];
          use_cases: string[];
          pricing_info: Record<string, any> | null;
          tutorial_urls: string[];
          screenshots: string[];
          demo_video_url: string | null;
          comparison_data: Record<string, any> | null;
          website_url: string | null;
          is_featured: boolean;
          is_active: boolean;
          order_index: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database['public']['Tables']['ai_tools']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['ai_tools']['Insert']>;
      };
      lessons: {
        Row: {
          id: string;
          slug: string;
          title: string;
          title_chinese: string | null;
          description: string | null;
          description_chinese: string | null;
          lesson_type: 'online' | 'offline' | 'hybrid';
          cover_image_url: string | null;
          instructor_id: string | null;
          duration_minutes: number | null;
          difficulty_level: 'beginner' | 'intermediate' | 'advanced' | null;
          price: number | null;
          currency: string;
          max_participants: number | null;
          registration_deadline: string | null;
          start_date: string | null;
          end_date: string | null;
          location: string | null;
          location_chinese: string | null;
          is_published: boolean;
          is_featured: boolean;
          order_index: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['lessons']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['lessons']['Insert']>;
      };
      blog_posts: {
        Row: {
          id: string;
          slug: string;
          title: string;
          title_chinese: string | null;
          excerpt: string | null;
          excerpt_chinese: string | null;
          content: string;
          content_chinese: string | null;
          cover_image_url: string | null;
          author_id: string | null;
          category: string | null;
          tags: string[];
          seo_title: string | null;
          seo_description: string | null;
          seo_keywords: string | null;
          is_published: boolean;
          published_at: string | null;
          view_count: number;
          is_featured: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['blog_posts']['Row'], 'id' | 'created_at' | 'updated_at' | 'view_count'>;
        Update: Partial<Database['public']['Tables']['blog_posts']['Insert']>;
      };
      content_generation_jobs: {
        Row: {
          id: string;
          job_type: 'blog_post' | 'tool_description' | 'image' | 'seo_content';
          target_type: string | null;
          target_id: string | null;
          prompt: string;
          status: 'pending' | 'processing' | 'completed' | 'failed';
          result_data: Record<string, any> | null;
          error_message: string | null;
          created_by: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['content_generation_jobs']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['content_generation_jobs']['Insert']>;
      };
      images: {
        Row: {
          id: string;
          filename: string;
          original_filename: string;
          storage_path: string;
          url: string;
          mime_type: string | null;
          file_size: number | null;
          width: number | null;
          height: number | null;
          alt_text: string | null;
          alt_text_chinese: string | null;
          category: string | null;
          tags: string[];
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['images']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['images']['Insert']>;
      };
      lesson_registrations: {
        Row: {
          id: string;
          lesson_id: string;
          user_id: string;
          status: 'registered' | 'attended' | 'completed' | 'cancelled';
          progress_percentage: number;
          registered_at: string;
          completed_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['lesson_registrations']['Row'], 'id' | 'registered_at'>;
        Update: Partial<Database['public']['Tables']['lesson_registrations']['Insert']>;
      };
      pages: {
        Row: {
          id: string;
          slug: string;
          title: string;
          title_chinese: string | null;
          content: string | null;
          content_chinese: string | null;
          page_type: 'static' | 'landing' | 'custom';
          template_data: Record<string, any> | null;
          is_published: boolean;
          order_index: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database['public']['Tables']['pages']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['pages']['Insert']>;
      };
      lesson_content: {
        Row: {
          id: string;
          lesson_id: string;
          content_type: 'video' | 'text' | 'quiz' | 'material' | 'assignment';
          title: string;
          content: string | null;
          video_url: string | null;
          video_provider: string | null;
          material_urls: string[];
          order_index: number;
          is_required: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['lesson_content']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['lesson_content']['Insert']>;
      };
    };
  };
};

